---
  - name: "extract artifact into ec2 instance"
    become: yes
    shell:
      tar -xf artifact.tar.gz

  - name: "starting the application"
    become: yes
    shell: 
      npm install
      pm2 stop default
      pm2 start npm -- start